image: node:latest
pages:
  stage: deploy
  variables:
    NODE_ENV: "production"
  script:
    - npm ci --production=false
    - npm run build
  artifacts:
    paths:
      - public
  only:
    - main
