image: oven/bun:latest
pages:
  stage: deploy
  variables:
    NODE_ENV: "production"
  script:
    - bun install --frozen-lockfile
    - bun run build
  artifacts:
    paths:
      - public
  only:
    - main
